name: app_tareas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.10
  animations: ^2.0.8
  flutter_secure_storage: ^9.0.0   
  lottie: ^3.1.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - animations/happy.gif
  - animations/sad.gif
  - animations/angry.gif
  - animations/love.gif

    